<a href="https://colab.research.google.com/github/anonymous0905/Cancer-Prediction-using-genome-data/blob/main/Version-1.0/icmr_cancer_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## ***Connect to Drive***

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

## ***Import Packages***

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import preprocessing

## ***Importing Dataset using Pandas***

In [ ]:
dataset = pd.read_csv('/content/drive/MyDrive/Datasets/data_icmr.csv')
dataset

,Unnamed: 0,gene_0,gene_1,gene_2,gene_3,gene_4,gene_5,gene_6,gene_7,gene_8,...,gene_20521,gene_20522,gene_20523,gene_20524,gene_20525,gene_20526,gene_20527,gene_20528,gene_20529,gene_20530
0,sample_0,0.0,2.017209,3.265527,5.478487,10.431999,0.0,7.175175,0.591871,0.0,...,4.926711,8.210257,9.723516,7.220030,9.119813,12.003135,9.650743,8.921326,5.286759,0.000000
1,sample_1,0.0,0.592732,1.588421,7.586157,9.623011,0.0,6.816049,0.000000,0.0,...,4.593372,7.323865,9.740931,6.256586,8.381612,12.674552,10.517059,9.397854,2.094168,0.000000
2,sample_2,0.0,3.511759,4.327199,6.881787,9.870730,0.0,6.972130,0.452595,0.0,...,5.125213,8.127123,10.908640,5.401607,9.911597,9.045255,9.788359,10.090470,1.683023,0.000000
3,sample_3,0.0,3.663618,4.507649,6.659068,10.196184,0.0,7.843375,0.434882,0.0,...,6.076566,8.792959,10.141520,8.942805,9.601208,11.392682,9.694814,9.684365,3.292001,0.000000
4,sample_4,0.0,2.655741,2.821547,6.539454,9.738265,0.0,6.566967,0.360982,0.0,...,5.996032,8.891425,10.373790,7.181162,9.846910,11.922439,9.217749,9.461191,5.110372,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
796,sample_796,0.0,1.865642,2.718197,7.350099,10.006003,0.0,6.764792,0.496922,0.0,...,6.088133,9.118313,10.004852,4.484415,9.614701,12.031267,9.813063,10.092770,8.819269,0.000000
797,sample_797,0.0,3.942955,4.453807,6.346597,10.056868,0.0,7.320331,0.000000,0.0,...,6.371876,9.623335,9.823921,6.555327,9.064002,11.633422,10.317266,8.745983,9.659081,0.000000
798,sample_798,0.0,3.249582,3.707492,8.185901,9.504082,0.0,7.536589,1.811101,0.0,...,5.719386,8.610704,10.485517,3.589763,9.350636,12.180944,10.681194,9.466711,4.677458,0.586693
799,sample_799,0.0,2.590339,2.787976,7.318624,9.987136,0.0,9.213464,0.000000,0.0,...,5.785237,8.605387,11.004677,4.745888,9.626383,11.198279,10.335513,10.400581,5.718751,0.000000
800,sample_800,0.0,2.325242,3.805932,6.530246,9.560367,0.0,7.957027,0.000000,0.0,...,6.403075,8.594354,10.243079,9.139459,10.102934,11.641081,10.607358,9.844794,4.550716,0.000000

## ***Importing Labels using Pandas***

In [ ]:
labels = pd.read_csv('/content/drive/MyDrive/Datasets/labels.csv')
labels

     Unnamed: 0 Class
0      sample_0  PRAD
1      sample_1  LUAD
2      sample_2  PRAD
3      sample_3  PRAD
4      sample_4  BRCA
..          ...   ...
796  sample_796  BRCA
797  sample_797  LUAD
798  sample_798  COAD
799  sample_799  PRAD
800  sample_800  PRAD

[801 rows x 2 columns]

## ***Renaming Column Name in the Dataset***

In [ ]:
dataset.rename(columns = {'Unnamed: 0':'Cancer Type'}, inplace = True)
dataset

,Cancer Type,gene_0,gene_1,gene_2,gene_3,gene_4,gene_5,gene_6,gene_7,gene_8,...,gene_20521,gene_20522,gene_20523,gene_20524,gene_20525,gene_20526,gene_20527,gene_20528,gene_20529,gene_20530
0,sample_0,0.0,2.017209,3.265527,5.478487,10.431999,0.0,7.175175,0.591871,0.0,...,4.926711,8.210257,9.723516,7.220030,9.119813,12.003135,9.650743,8.921326,5.286759,0.000000
1,sample_1,0.0,0.592732,1.588421,7.586157,9.623011,0.0,6.816049,0.000000,0.0,...,4.593372,7.323865,9.740931,6.256586,8.381612,12.674552,10.517059,9.397854,2.094168,0.000000
2,sample_2,0.0,3.511759,4.327199,6.881787,9.870730,0.0,6.972130,0.452595,0.0,...,5.125213,8.127123,10.908640,5.401607,9.911597,9.045255,9.788359,10.090470,1.683023,0.000000
3,sample_3,0.0,3.663618,4.507649,6.659068,10.196184,0.0,7.843375,0.434882,0.0,...,6.076566,8.792959,10.141520,8.942805,9.601208,11.392682,9.694814,9.684365,3.292001,0.000000
4,sample_4,0.0,2.655741,2.821547,6.539454,9.738265,0.0,6.566967,0.360982,0.0,...,5.996032,8.891425,10.373790,7.181162,9.846910,11.922439,9.217749,9.461191,5.110372,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
796,sample_796,0.0,1.865642,2.718197,7.350099,10.006003,0.0,6.764792,0.496922,0.0,...,6.088133,9.118313,10.004852,4.484415,9.614701,12.031267,9.813063,10.092770,8.819269,0.000000
797,sample_797,0.0,3.942955,4.453807,6.346597,10.056868,0.0,7.320331,0.000000,0.0,...,6.371876,9.623335,9.823921,6.555327,9.064002,11.633422,10.317266,8.745983,9.659081,0.000000
798,sample_798,0.0,3.249582,3.707492,8.185901,9.504082,0.0,7.536589,1.811101,0.0,...,5.719386,8.610704,10.485517,3.589763,9.350636,12.180944,10.681194,9.466711,4.677458,0.586693
799,sample_799,0.0,2.590339,2.787976,7.318624,9.987136,0.0,9.213464,0.000000,0.0,...,5.785237,8.605387,11.004677,4.745888,9.626383,11.198279,10.335513,10.400581,5.718751,0.000000
800,sample_800,0.0,2.325242,3.805932,6.530246,9.560367,0.0,7.957027,0.000000,0.0,...,6.403075,8.594354,10.243079,9.139459,10.102934,11.641081,10.607358,9.844794,4.550716,0.000000

## ***Replacing Sample Labels with Cancer Type***

In [ ]:
for i in range (0,801):
  #dataset.iat[i,0] = labels.iat[i,1]
  dataset['Cancer Type'] = dataset['Cancer Type'].replace(dataset.iat[i,0], labels.iat[i,1])
dataset

,Cancer Type,gene_0,gene_1,gene_2,gene_3,gene_4,gene_5,gene_6,gene_7,gene_8,...,gene_20521,gene_20522,gene_20523,gene_20524,gene_20525,gene_20526,gene_20527,gene_20528,gene_20529,gene_20530
0,PRAD,0.0,2.017209,3.265527,5.478487,10.431999,0.0,7.175175,0.591871,0.0,...,4.926711,8.210257,9.723516,7.220030,9.119813,12.003135,9.650743,8.921326,5.286759,0.000000
1,LUAD,0.0,0.592732,1.588421,7.586157,9.623011,0.0,6.816049,0.000000,0.0,...,4.593372,7.323865,9.740931,6.256586,8.381612,12.674552,10.517059,9.397854,2.094168,0.000000
2,PRAD,0.0,3.511759,4.327199,6.881787,9.870730,0.0,6.972130,0.452595,0.0,...,5.125213,8.127123,10.908640,5.401607,9.911597,9.045255,9.788359,10.090470,1.683023,0.000000
3,PRAD,0.0,3.663618,4.507649,6.659068,10.196184,0.0,7.843375,0.434882,0.0,...,6.076566,8.792959,10.141520,8.942805,9.601208,11.392682,9.694814,9.684365,3.292001,0.000000
4,BRCA,0.0,2.655741,2.821547,6.539454,9.738265,0.0,6.566967,0.360982,0.0,...,5.996032,8.891425,10.373790,7.181162,9.846910,11.922439,9.217749,9.461191,5.110372,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
796,BRCA,0.0,1.865642,2.718197,7.350099,10.006003,0.0,6.764792,0.496922,0.0,...,6.088133,9.118313,10.004852,4.484415,9.614701,12.031267,9.813063,10.092770,8.819269,0.000000
797,LUAD,0.0,3.942955,4.453807,6.346597,10.056868,0.0,7.320331,0.000000,0.0,...,6.371876,9.623335,9.823921,6.555327,9.064002,11.633422,10.317266,8.745983,9.659081,0.000000
798,COAD,0.0,3.249582,3.707492,8.185901,9.504082,0.0,7.536589,1.811101,0.0,...,5.719386,8.610704,10.485517,3.589763,9.350636,12.180944,10.681194,9.466711,4.677458,0.586693
799,PRAD,0.0,2.590339,2.787976,7.318624,9.987136,0.0,9.213464,0.000000,0.0,...,5.785237,8.605387,11.004677,4.745888,9.626383,11.198279,10.335513,10.400581,5.718751,0.000000
800,PRAD,0.0,2.325242,3.805932,6.530246,9.560367,0.0,7.957027,0.000000,0.0,...,6.403075,8.594354,10.243079,9.139459,10.102934,11.641081,10.607358,9.844794,4.550716,0.000000

## ***Checking for NaN Values***

In [ ]:
for col in dataset.columns:
  if dataset[col].isnull().sum() > 0:
    print(col)
# No NaN Values found

## ***Encoding Categorical Data using Label Transformer***

In [ ]:
dataset['Cancer Type'].unique()
le = preprocessing.LabelEncoder()
le.fit(dataset['Cancer Type'])
print(le.classes_)
encoded_cancer_type = le.transform(dataset['Cancer Type'])
for i in range (0,801):
  #dataset.iat[i,0] = labels.iat[i,1]
  dataset['Cancer Type'] = dataset['Cancer Type'].replace(dataset.iat[i,0], encoded_cancer_type[i])
dataset

[0 1 2 3 4]

,Cancer Type,gene_0,gene_1,gene_2,gene_3,gene_4,gene_5,gene_6,gene_7,gene_8,...,gene_20521,gene_20522,gene_20523,gene_20524,gene_20525,gene_20526,gene_20527,gene_20528,gene_20529,gene_20530
0,4,0.0,2.017209,3.265527,5.478487,10.431999,0.0,7.175175,0.591871,0.0,...,4.926711,8.210257,9.723516,7.220030,9.119813,12.003135,9.650743,8.921326,5.286759,0.000000
1,3,0.0,0.592732,1.588421,7.586157,9.623011,0.0,6.816049,0.000000,0.0,...,4.593372,7.323865,9.740931,6.256586,8.381612,12.674552,10.517059,9.397854,2.094168,0.000000
2,4,0.0,3.511759,4.327199,6.881787,9.870730,0.0,6.972130,0.452595,0.0,...,5.125213,8.127123,10.908640,5.401607,9.911597,9.045255,9.788359,10.090470,1.683023,0.000000
3,4,0.0,3.663618,4.507649,6.659068,10.196184,0.0,7.843375,0.434882,0.0,...,6.076566,8.792959,10.141520,8.942805,9.601208,11.392682,9.694814,9.684365,3.292001,0.000000
4,0,0.0,2.655741,2.821547,6.539454,9.738265,0.0,6.566967,0.360982,0.0,...,5.996032,8.891425,10.373790,7.181162,9.846910,11.922439,9.217749,9.461191,5.110372,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
796,0,0.0,1.865642,2.718197,7.350099,10.006003,0.0,6.764792,0.496922,0.0,...,6.088133,9.118313,10.004852,4.484415,9.614701,12.031267,9.813063,10.092770,8.819269,0.000000
797,3,0.0,3.942955,4.453807,6.346597,10.056868,0.0,7.320331,0.000000,0.0,...,6.371876,9.623335,9.823921,6.555327,9.064002,11.633422,10.317266,8.745983,9.659081,0.000000
798,1,0.0,3.249582,3.707492,8.185901,9.504082,0.0,7.536589,1.811101,0.0,...,5.719386,8.610704,10.485517,3.589763,9.350636,12.180944,10.681194,9.466711,4.677458,0.586693
799,4,0.0,2.590339,2.787976,7.318624,9.987136,0.0,9.213464,0.000000,0.0,...,5.785237,8.605387,11.004677,4.745888,9.626383,11.198279,10.335513,10.400581,5.718751,0.000000
800,4,0.0,2.325242,3.805932,6.530246,9.560367,0.0,7.957027,0.000000,0.0,...,6.403075,8.594354,10.243079,9.139459,10.102934,11.641081,10.607358,9.844794,4.550716,0.000000

## ***Split Dataset into Training Data and Test Data***

In [ ]:
from sklearn.model_selection import train_test_split
dataset_train, dataset_test = train_test_split(dataset,test_size=0.2, shuffle=True, random_state=1)

## ***Training Data***

In [ ]:
dataset_train

,Cancer Type,gene_0,gene_1,gene_2,gene_3,gene_4,gene_5,gene_6,gene_7,gene_8,...,gene_20521,gene_20522,gene_20523,gene_20524,gene_20525,gene_20526,gene_20527,gene_20528,gene_20529,gene_20530
309,0,0.000000,3.489029,3.511177,6.337722,10.198101,0.0,9.471700,0.000000,0.0,...,4.434948,7.963723,10.022493,6.094196,9.596326,11.963402,9.870138,9.515162,8.722060,0.000000
582,0,0.000000,5.774405,5.229730,6.083894,9.410716,0.0,5.759489,0.000000,0.0,...,5.698727,8.398577,10.455368,3.803020,9.472817,11.218587,10.864743,9.918766,4.272016,0.000000
593,0,0.000000,3.317434,3.038225,7.709615,10.256680,0.0,5.849079,0.834388,0.0,...,4.918157,8.475729,10.745893,7.986838,10.629484,11.430625,9.690192,11.158635,9.776882,0.000000
108,3,0.000000,2.480989,2.560446,7.026789,10.046537,0.0,5.643527,0.000000,0.0,...,5.222897,7.781530,9.610392,5.847346,9.966315,11.994916,9.122202,8.844226,4.175285,0.000000
798,1,0.000000,3.249582,3.707492,8.185901,9.504082,0.0,7.536589,1.811101,0.0,...,5.719386,8.610704,10.485517,3.589763,9.350636,12.180944,10.681194,9.466711,4.677458,0.586693
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
715,4,0.000000,4.748901,4.713602,6.453623,9.522389,0.0,8.807806,1.662844,0.0,...,6.247105,8.859861,10.410971,5.028087,9.772288,11.934078,10.825166,9.481876,8.142766,0.000000
767,1,0.000000,4.672505,5.151839,7.273012,9.688172,0.0,7.402969,0.000000,0.0,...,4.100641,8.951722,10.611237,1.417542,9.524299,12.566839,10.481204,9.616262,4.276824,0.000000
72,0,1.482332,2.907198,4.034365,6.613129,9.456295,0.0,10.038850,0.000000,0.0,...,5.147535,7.685660,10.155552,6.664853,8.469345,12.737940,10.332171,8.624295,8.378936,0.000000
235,4,0.000000,3.389553,3.391355,7.062424,9.286528,0.0,6.831067,0.000000,0.0,...,6.399429,8.872764,9.757512,6.017655,10.440807,11.695093,10.471381,9.785054,6.537920,0.000000
37,3,0.000000,4.416259,4.188978,6.664198,9.070819,0.0,7.915318,0.906275,0.0,...,5.786609,8.302470,10.431884,2.168899,9.402496,12.072283,10.637458,9.379959,6.148450,0.906275

## ***Testing Data***

In [ ]:
dataset_test

,Cancer Type,gene_0,gene_1,gene_2,gene_3,gene_4,gene_5,gene_6,gene_7,gene_8,...,gene_20521,gene_20522,gene_20523,gene_20524,gene_20525,gene_20526,gene_20527,gene_20528,gene_20529,gene_20530
8,0,0.0,3.992125,2.772730,6.546692,10.488252,0.0,7.690222,0.352307,0.0,...,6.721974,9.597533,9.763753,7.933278,10.952880,12.498919,10.389954,10.390255,7.828321,0.000000
788,4,0.0,4.869200,4.087717,6.369039,9.684507,0.0,7.929903,0.000000,0.0,...,6.029753,8.875998,10.766554,6.197223,10.013392,9.939708,10.591896,10.316972,3.412782,0.000000
570,1,0.0,3.223716,3.027490,9.173387,10.057410,0.0,7.236426,0.600745,0.0,...,5.940963,8.564466,10.373311,0.000000,8.904803,11.991256,10.228650,9.914923,3.950730,0.000000
224,3,0.0,2.126246,3.513529,6.071696,9.565211,0.0,7.698996,0.000000,0.0,...,6.427449,8.759602,9.855941,7.042207,10.049181,13.044889,10.373757,10.077737,4.234279,0.418136
496,4,0.0,4.279924,3.606963,5.706613,9.716581,0.0,8.244226,0.402613,0.0,...,5.979975,8.461332,10.034744,4.809193,9.926295,10.827517,10.476949,9.734679,9.181547,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
671,0,0.0,2.526920,2.660381,6.667552,9.647475,0.0,7.609821,0.000000,0.0,...,6.192766,9.793984,10.003110,5.559486,9.733475,11.646473,10.550958,9.779411,5.511221,0.000000
364,2,0.0,0.000000,2.275752,6.025051,10.181674,0.0,6.112777,0.565890,0.0,...,5.402804,7.875964,10.120121,2.412185,9.498614,12.894869,10.434430,9.048045,7.690501,0.000000
674,4,0.0,4.229896,4.028003,7.032894,9.754323,0.0,7.567378,0.612777,0.0,...,6.524023,9.406613,10.242114,6.635736,10.744834,10.559951,10.714941,10.237688,6.260805,0.000000
41,4,0.0,3.026375,4.364103,7.164917,9.552402,0.0,7.903520,0.638862,0.0,...,5.867442,8.526257,9.960788,5.960727,9.934746,11.477040,10.126692,9.417869,8.367406,0.000000
666,3,0.0,3.798320,4.743278,7.034755,9.537941,0.0,9.337464,0.000000,0.0,...,6.418467,9.279216,10.021327,6.142683,9.255524,11.276090,9.865248,9.488581,3.311779,0.673828

## ***Extracting Data for each cancer type***

In [ ]:
cancer_type0 = dataset_train.loc[dataset_train['Cancer Type']==0]
cancer_type0

,Cancer Type,gene_0,gene_1,gene_2,gene_3,gene_4,gene_5,gene_6,gene_7,gene_8,...,gene_20521,gene_20522,gene_20523,gene_20524,gene_20525,gene_20526,gene_20527,gene_20528,gene_20529,gene_20530
309,0,0.000000,3.489029,3.511177,6.337722,10.198101,0.0,9.471700,0.000000,0.0,...,4.434948,7.963723,10.022493,6.094196,9.596326,11.963402,9.870138,9.515162,8.722060,0.0
582,0,0.000000,5.774405,5.229730,6.083894,9.410716,0.0,5.759489,0.000000,0.0,...,5.698727,8.398577,10.455368,3.803020,9.472817,11.218587,10.864743,9.918766,4.272016,0.0
593,0,0.000000,3.317434,3.038225,7.709615,10.256680,0.0,5.849079,0.834388,0.0,...,4.918157,8.475729,10.745893,7.986838,10.629484,11.430625,9.690192,11.158635,9.776882,0.0
415,0,0.000000,3.432853,2.625317,6.560503,9.356725,0.0,7.853615,0.898092,0.0,...,6.786492,10.360057,10.176298,5.784509,9.896764,11.764971,10.828636,9.409588,4.765349,0.0
708,0,0.000000,4.248467,4.066485,6.110987,9.470641,0.0,7.664013,1.176195,0.0,...,6.225393,8.835362,10.373431,6.230243,10.063449,11.721706,10.937514,10.336239,6.082520,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
668,0,0.000000,3.824035,3.300241,6.630478,9.836429,0.0,7.969214,0.404576,0.0,...,5.912710,8.904328,10.066385,6.568055,9.963020,11.601093,9.570746,10.002717,5.385082,0.0
276,0,0.565890,3.885106,2.977829,6.047855,10.115135,0.0,7.458054,0.971295,0.0,...,5.954173,9.050662,10.572331,6.152283,10.298532,12.111028,9.800851,10.231521,4.966218,0.0
178,0,0.000000,1.402722,1.108357,6.785655,10.285633,0.0,5.892391,0.000000,0.0,...,5.902074,8.536830,9.967226,3.510962,9.671364,12.007658,9.812819,9.796689,4.916477,0.0
281,0,0.000000,4.649794,4.912161,6.712169,8.983051,0.0,7.717711,0.000000,0.0,...,6.392295,9.228970,10.643008,5.590626,10.110810,12.525335,10.672001,10.091911,7.342626,0.0
72,0,1.482332,2.907198,4.034365,6.613129,9.456295,0.0,10.038850,0.000000,0.0,...,5.147535,7.685660,10.155552,6.664853,8.469345,12.737940,10.332171,8.624295,8.378936,0.0

In [ ]:
cancer_type1 = dataset_train.loc[dataset_train['Cancer Type']==1]
cancer_type1

,Cancer Type,gene_0,gene_1,gene_2,gene_3,gene_4,gene_5,gene_6,gene_7,gene_8,...,gene_20521,gene_20522,gene_20523,gene_20524,gene_20525,gene_20526,gene_20527,gene_20528,gene_20529,gene_20530
798,1,0.0,3.249582,3.707492,8.185901,9.504082,0.0,7.536589,1.811101,0.0,...,5.719386,8.610704,10.485517,3.589763,9.350636,12.180944,10.681194,9.466711,4.677458,0.586693
363,1,0.0,3.126494,1.731965,7.861931,9.872632,0.0,7.710187,0.543001,0.0,...,4.940519,8.055727,9.595062,0.543001,9.069063,13.327272,10.385194,8.952785,5.195702,0.000000
353,1,0.0,3.006388,3.594023,7.673132,9.559761,0.0,8.405456,0.550310,0.0,...,5.553800,8.764002,9.789092,1.920789,9.279427,12.118331,10.956507,8.974423,2.814961,0.550310
132,1,0.0,1.624335,2.880039,7.849242,9.961128,0.0,7.426315,0.000000,0.0,...,5.710732,8.710858,9.516045,0.768671,8.638823,12.131397,10.235763,9.007652,2.728965,0.000000
473,1,0.0,2.676696,0.000000,7.318823,10.005737,0.0,7.670437,0.535555,0.0,...,6.048234,8.452254,9.713809,0.535555,9.133173,12.899708,10.082508,8.774468,6.058000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
264,1,0.0,3.160243,2.672516,8.319076,10.240469,0.0,7.165138,0.000000,0.0,...,5.813361,8.684072,9.851277,0.578407,8.915327,12.609366,10.623086,9.072915,5.406850,0.000000
503,1,0.0,3.528596,3.197740,7.761365,10.226846,0.0,5.899620,0.511367,0.0,...,4.027915,7.597561,9.785864,0.000000,9.039764,11.961381,11.377368,8.637632,3.182962,0.000000
490,1,0.0,4.885818,4.505967,7.826765,9.496209,0.0,7.178993,0.494467,0.0,...,5.208560,8.253469,9.893488,1.397967,9.282699,11.908396,11.455764,9.409535,2.347184,0.000000
252,1,0.0,2.408821,2.340505,7.189518,9.806505,0.0,6.386042,0.000000,0.0,...,5.924651,8.563932,9.746817,1.081817,9.899683,13.600680,10.624183,9.190993,6.719882,0.000000
767,1,0.0,4.672505,5.151839,7.273012,9.688172,0.0,7.402969,0.000000,0.0,...,4.100641,8.951722,10.611237,1.417542,9.524299,12.566839,10.481204,9.616262,4.276824,0.000000

In [ ]:
cancer_type2 = dataset_train.loc[dataset_train['Cancer Type']==2]
cancer_type2

,Cancer Type,gene_0,gene_1,gene_2,gene_3,gene_4,gene_5,gene_6,gene_7,gene_8,...,gene_20521,gene_20522,gene_20523,gene_20524,gene_20525,gene_20526,gene_20527,gene_20528,gene_20529,gene_20530
430,2,0.000000,0.000000,1.304219,6.948683,9.122106,0.0,4.571549,0.000000,0.0,...,6.667651,8.744847,9.989849,0.000000,10.449324,11.418917,9.933509,9.437030,6.225822,0.451435
555,2,0.000000,2.245800,1.760647,7.105594,8.983837,0.0,5.342569,0.000000,0.0,...,7.313128,8.994913,9.982010,5.261031,10.694428,11.279582,10.409656,9.920692,5.447652,0.000000
482,2,0.000000,2.537495,1.543793,6.172257,9.934568,0.0,4.982761,0.000000,0.0,...,5.704806,8.371110,9.701464,4.680623,9.867524,11.935802,10.213967,9.128319,5.619715,0.000000
592,2,0.000000,3.640656,2.129019,6.048334,9.937914,0.0,8.953853,0.925848,0.0,...,5.695935,8.018139,10.198163,1.485221,9.501594,12.449218,9.830807,9.312427,8.658583,0.000000
223,2,0.000000,2.870404,1.268614,6.516157,9.287569,0.0,6.674658,0.825541,0.0,...,7.017599,8.560134,9.703589,5.989782,10.192428,11.646392,10.495325,9.885373,4.199633,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
534,2,0.553164,3.733398,3.450472,6.064193,9.349929,0.0,7.348533,0.539730,0.0,...,7.588490,8.825954,10.269910,4.747500,10.845435,11.833432,10.578920,9.588820,4.450954,0.000000
319,2,0.000000,3.095891,3.216827,6.195979,9.328709,0.0,7.973296,1.149910,0.0,...,6.438584,8.585631,10.121482,0.858140,9.814147,12.045391,10.470781,8.816398,6.610415,0.000000
468,2,0.000000,2.239092,0.857424,5.902045,8.871265,0.0,4.685066,0.000000,0.0,...,7.769263,9.315698,9.530281,4.976982,10.540128,11.396583,10.654824,9.584716,6.175700,0.000000
357,2,0.000000,1.328549,2.744506,7.075661,8.992080,0.0,5.667781,0.000000,0.0,...,6.809247,8.698448,10.243353,3.714916,10.214186,11.082508,10.285645,9.419821,4.899780,0.000000
583,2,0.000000,1.764941,1.935007,6.477630,9.175118,0.0,5.640011,0.000000,0.0,...,6.620012,8.797357,10.165924,2.123434,10.509824,11.792546,10.774787,8.957479,5.859811,0.000000

In [ ]:
cancer_type3 = dataset_train.loc[dataset_train['Cancer Type']==3]
cancer_type3

,Cancer Type,gene_0,gene_1,gene_2,gene_3,gene_4,gene_5,gene_6,gene_7,gene_8,...,gene_20521,gene_20522,gene_20523,gene_20524,gene_20525,gene_20526,gene_20527,gene_20528,gene_20529,gene_20530
108,3,0.0,2.480989,2.560446,7.026789,10.046537,0.0,5.643527,0.000000,0.0,...,5.222897,7.781530,9.610392,5.847346,9.966315,11.994916,9.122202,8.844226,4.175285,0.000000
345,3,0.0,4.667773,5.567518,5.565984,9.665277,0.0,7.357754,0.374511,0.0,...,6.130573,8.547569,10.124225,0.917775,10.049522,11.743547,9.308619,9.793686,4.423040,0.374511
187,3,0.0,3.889172,4.101171,6.573458,9.592337,0.0,7.489447,0.371726,0.0,...,5.407414,8.202712,9.513309,6.682208,9.736497,12.172896,10.089265,8.981156,4.196993,0.371726
159,3,0.0,3.755902,4.589122,6.440992,9.438946,0.0,8.335864,0.560128,0.0,...,5.667046,8.342204,10.147587,6.502369,9.999013,12.114276,10.344673,9.110374,5.013878,0.000000
161,3,0.0,5.425563,5.203863,6.755048,9.243736,0.0,7.658547,0.431890,0.0,...,5.906597,8.818937,11.150096,2.166844,9.734642,10.692092,11.384946,9.544095,10.030709,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
749,3,0.0,3.576764,3.645598,6.623074,10.169587,0.0,6.504433,0.000000,0.0,...,6.588062,9.058747,10.039467,5.234107,9.390846,10.480104,10.538839,8.975415,4.042706,0.000000
129,3,0.0,3.299406,2.633571,7.820198,9.845145,0.0,8.121984,0.753091,0.0,...,4.738903,8.064048,9.735744,2.146329,10.007644,12.251761,9.049269,10.032886,0.753091,0.000000
144,3,0.0,3.947741,4.117105,6.607986,9.018732,0.0,7.392815,0.000000,0.0,...,6.527083,9.248910,9.947752,4.277620,10.526734,11.974916,10.187228,9.673118,6.198773,0.000000
645,3,0.0,4.232154,2.558488,6.453183,9.395063,0.0,8.572852,0.426211,0.0,...,5.942315,9.070169,10.237676,7.047604,10.481567,11.877464,10.307816,10.217000,3.813597,0.000000
37,3,0.0,4.416259,4.188978,6.664198,9.070819,0.0,7.915318,0.906275,0.0,...,5.786609,8.302470,10.431884,2.168899,9.402496,12.072283,10.637458,9.379959,6.148450,0.906275

In [ ]:
cancer_type4 = dataset_train.loc[dataset_train['Cancer Type']==4]
cancer_type4

,Cancer Type,gene_0,gene_1,gene_2,gene_3,gene_4,gene_5,gene_6,gene_7,gene_8,...,gene_20521,gene_20522,gene_20523,gene_20524,gene_20525,gene_20526,gene_20527,gene_20528,gene_20529,gene_20530
0,4,0.0,2.017209,3.265527,5.478487,10.431999,0.0,7.175175,0.591871,0.0,...,4.926711,8.210257,9.723516,7.220030,9.119813,12.003135,9.650743,8.921326,5.286759,0.000000
587,4,0.0,3.763465,3.720738,6.991919,10.087038,0.0,7.120881,0.000000,0.0,...,6.378839,8.830309,9.951436,5.630490,10.238441,11.762179,10.789289,10.123358,5.856958,0.000000
714,4,0.0,4.541986,5.503727,6.443520,9.809308,0.0,8.591765,0.882760,0.0,...,6.209389,8.825747,10.189429,7.083224,9.767315,11.070101,10.653875,10.027395,6.176101,0.000000
657,4,0.0,4.243806,4.525637,7.338389,9.349832,0.0,7.602283,0.336855,0.0,...,6.769521,9.250538,10.238715,7.103361,10.284153,11.300524,10.717505,9.360263,4.852004,0.336855
125,4,0.0,3.733853,3.339123,6.844925,9.435404,0.0,8.799936,0.000000,0.0,...,5.666680,8.238882,9.746741,6.306886,9.840839,11.691443,9.883031,9.589732,7.198867,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
478,4,0.0,3.930822,4.049578,6.732256,9.806242,0.0,6.808784,0.000000,0.0,...,6.683977,9.104234,10.160666,4.203326,10.076268,11.021549,10.765568,10.210075,5.520705,0.000000
254,4,0.0,5.006132,5.848044,6.300243,9.740403,0.0,8.433961,0.781737,0.0,...,6.310869,8.810700,10.567348,6.742505,9.699185,10.491903,10.610462,9.846200,4.649161,0.000000
390,4,0.0,1.539978,5.155300,6.317101,9.685618,0.0,8.430833,0.000000,0.0,...,5.465628,8.477685,9.871063,6.540306,9.603504,12.018245,10.197499,9.431719,6.969784,0.000000
715,4,0.0,4.748901,4.713602,6.453623,9.522389,0.0,8.807806,1.662844,0.0,...,6.247105,8.859861,10.410971,5.028087,9.772288,11.934078,10.825166,9.481876,8.142766,0.000000
235,4,0.0,3.389553,3.391355,7.062424,9.286528,0.0,6.831067,0.000000,0.0,...,6.399429,8.872764,9.757512,6.017655,10.440807,11.695093,10.471381,9.785054,6.537920,0.000000