<a href="https://colab.research.google.com/github/anonymous0905/Cancer-Prediction-using-genome-data/blob/main/v1.2/icmr_cancer_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## ***Connect to Drive***

In [51]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

## ***Import Packages***

In [52]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import preprocessing

## ***Importing Dataset using Pandas***

In [53]:
dataset = pd.read_csv('/content/drive/MyDrive/Datasets/data_icmr.csv')
dataset

,Unnamed: 0,gene_0,gene_1,gene_2,gene_3,gene_4,gene_5,gene_6,gene_7,gene_8,...,gene_20521,gene_20522,gene_20523,gene_20524,gene_20525,gene_20526,gene_20527,gene_20528,gene_20529,gene_20530
0,sample_0,0.0,2.017209,3.265527,5.478487,10.431999,0.0,7.175175,0.591871,0.0,...,4.926711,8.210257,9.723516,7.220030,9.119813,12.003135,9.650743,8.921326,5.286759,0.000000
1,sample_1,0.0,0.592732,1.588421,7.586157,9.623011,0.0,6.816049,0.000000,0.0,...,4.593372,7.323865,9.740931,6.256586,8.381612,12.674552,10.517059,9.397854,2.094168,0.000000
2,sample_2,0.0,3.511759,4.327199,6.881787,9.870730,0.0,6.972130,0.452595,0.0,...,5.125213,8.127123,10.908640,5.401607,9.911597,9.045255,9.788359,10.090470,1.683023,0.000000
3,sample_3,0.0,3.663618,4.507649,6.659068,10.196184,0.0,7.843375,0.434882,0.0,...,6.076566,8.792959,10.141520,8.942805,9.601208,11.392682,9.694814,9.684365,3.292001,0.000000
4,sample_4,0.0,2.655741,2.821547,6.539454,9.738265,0.0,6.566967,0.360982,0.0,...,5.996032,8.891425,10.373790,7.181162,9.846910,11.922439,9.217749,9.461191,5.110372,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
796,sample_796,0.0,1.865642,2.718197,7.350099,10.006003,0.0,6.764792,0.496922,0.0,...,6.088133,9.118313,10.004852,4.484415,9.614701,12.031267,9.813063,10.092770,8.819269,0.000000
797,sample_797,0.0,3.942955,4.453807,6.346597,10.056868,0.0,7.320331,0.000000,0.0,...,6.371876,9.623335,9.823921,6.555327,9.064002,11.633422,10.317266,8.745983,9.659081,0.000000
798,sample_798,0.0,3.249582,3.707492,8.185901,9.504082,0.0,7.536589,1.811101,0.0,...,5.719386,8.610704,10.485517,3.589763,9.350636,12.180944,10.681194,9.466711,4.677458,0.586693
799,sample_799,0.0,2.590339,2.787976,7.318624,9.987136,0.0,9.213464,0.000000,0.0,...,5.785237,8.605387,11.004677,4.745888,9.626383,11.198279,10.335513,10.400581,5.718751,0.000000
800,sample_800,0.0,2.325242,3.805932,6.530246,9.560367,0.0,7.957027,0.000000,0.0,...,6.403075,8.594354,10.243079,9.139459,10.102934,11.641081,10.607358,9.844794,4.550716,0.000000

## ***Importing Labels using Pandas***

In [54]:
labels = pd.read_csv('/content/drive/MyDrive/Datasets/labels.csv')
labels

     Unnamed: 0 Class
0      sample_0  PRAD
1      sample_1  LUAD
2      sample_2  PRAD
3      sample_3  PRAD
4      sample_4  BRCA
..          ...   ...
796  sample_796  BRCA
797  sample_797  LUAD
798  sample_798  COAD
799  sample_799  PRAD
800  sample_800  PRAD

[801 rows x 2 columns]

## ***Renaming Column Name in the Dataset***

In [55]:
dataset.rename(columns = {'Unnamed: 0':'Cancer Type'}, inplace = True)
dataset

,Cancer Type,gene_0,gene_1,gene_2,gene_3,gene_4,gene_5,gene_6,gene_7,gene_8,...,gene_20521,gene_20522,gene_20523,gene_20524,gene_20525,gene_20526,gene_20527,gene_20528,gene_20529,gene_20530
0,sample_0,0.0,2.017209,3.265527,5.478487,10.431999,0.0,7.175175,0.591871,0.0,...,4.926711,8.210257,9.723516,7.220030,9.119813,12.003135,9.650743,8.921326,5.286759,0.000000
1,sample_1,0.0,0.592732,1.588421,7.586157,9.623011,0.0,6.816049,0.000000,0.0,...,4.593372,7.323865,9.740931,6.256586,8.381612,12.674552,10.517059,9.397854,2.094168,0.000000
2,sample_2,0.0,3.511759,4.327199,6.881787,9.870730,0.0,6.972130,0.452595,0.0,...,5.125213,8.127123,10.908640,5.401607,9.911597,9.045255,9.788359,10.090470,1.683023,0.000000
3,sample_3,0.0,3.663618,4.507649,6.659068,10.196184,0.0,7.843375,0.434882,0.0,...,6.076566,8.792959,10.141520,8.942805,9.601208,11.392682,9.694814,9.684365,3.292001,0.000000
4,sample_4,0.0,2.655741,2.821547,6.539454,9.738265,0.0,6.566967,0.360982,0.0,...,5.996032,8.891425,10.373790,7.181162,9.846910,11.922439,9.217749,9.461191,5.110372,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
796,sample_796,0.0,1.865642,2.718197,7.350099,10.006003,0.0,6.764792,0.496922,0.0,...,6.088133,9.118313,10.004852,4.484415,9.614701,12.031267,9.813063,10.092770,8.819269,0.000000
797,sample_797,0.0,3.942955,4.453807,6.346597,10.056868,0.0,7.320331,0.000000,0.0,...,6.371876,9.623335,9.823921,6.555327,9.064002,11.633422,10.317266,8.745983,9.659081,0.000000
798,sample_798,0.0,3.249582,3.707492,8.185901,9.504082,0.0,7.536589,1.811101,0.0,...,5.719386,8.610704,10.485517,3.589763,9.350636,12.180944,10.681194,9.466711,4.677458,0.586693
799,sample_799,0.0,2.590339,2.787976,7.318624,9.987136,0.0,9.213464,0.000000,0.0,...,5.785237,8.605387,11.004677,4.745888,9.626383,11.198279,10.335513,10.400581,5.718751,0.000000
800,sample_800,0.0,2.325242,3.805932,6.530246,9.560367,0.0,7.957027,0.000000,0.0,...,6.403075,8.594354,10.243079,9.139459,10.102934,11.641081,10.607358,9.844794,4.550716,0.000000

## ***Replacing Sample Labels with Cancer Type***

In [56]:
for i in range (0,801):
  #dataset.iat[i,0] = labels.iat[i,1]
  dataset['Cancer Type'] = dataset['Cancer Type'].replace(dataset.iat[i,0], labels.iat[i,1])
dataset

,Cancer Type,gene_0,gene_1,gene_2,gene_3,gene_4,gene_5,gene_6,gene_7,gene_8,...,gene_20521,gene_20522,gene_20523,gene_20524,gene_20525,gene_20526,gene_20527,gene_20528,gene_20529,gene_20530
0,PRAD,0.0,2.017209,3.265527,5.478487,10.431999,0.0,7.175175,0.591871,0.0,...,4.926711,8.210257,9.723516,7.220030,9.119813,12.003135,9.650743,8.921326,5.286759,0.000000
1,LUAD,0.0,0.592732,1.588421,7.586157,9.623011,0.0,6.816049,0.000000,0.0,...,4.593372,7.323865,9.740931,6.256586,8.381612,12.674552,10.517059,9.397854,2.094168,0.000000
2,PRAD,0.0,3.511759,4.327199,6.881787,9.870730,0.0,6.972130,0.452595,0.0,...,5.125213,8.127123,10.908640,5.401607,9.911597,9.045255,9.788359,10.090470,1.683023,0.000000
3,PRAD,0.0,3.663618,4.507649,6.659068,10.196184,0.0,7.843375,0.434882,0.0,...,6.076566,8.792959,10.141520,8.942805,9.601208,11.392682,9.694814,9.684365,3.292001,0.000000
4,BRCA,0.0,2.655741,2.821547,6.539454,9.738265,0.0,6.566967,0.360982,0.0,...,5.996032,8.891425,10.373790,7.181162,9.846910,11.922439,9.217749,9.461191,5.110372,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
796,BRCA,0.0,1.865642,2.718197,7.350099,10.006003,0.0,6.764792,0.496922,0.0,...,6.088133,9.118313,10.004852,4.484415,9.614701,12.031267,9.813063,10.092770,8.819269,0.000000
797,LUAD,0.0,3.942955,4.453807,6.346597,10.056868,0.0,7.320331,0.000000,0.0,...,6.371876,9.623335,9.823921,6.555327,9.064002,11.633422,10.317266,8.745983,9.659081,0.000000
798,COAD,0.0,3.249582,3.707492,8.185901,9.504082,0.0,7.536589,1.811101,0.0,...,5.719386,8.610704,10.485517,3.589763,9.350636,12.180944,10.681194,9.466711,4.677458,0.586693
799,PRAD,0.0,2.590339,2.787976,7.318624,9.987136,0.0,9.213464,0.000000,0.0,...,5.785237,8.605387,11.004677,4.745888,9.626383,11.198279,10.335513,10.400581,5.718751,0.000000
800,PRAD,0.0,2.325242,3.805932,6.530246,9.560367,0.0,7.957027,0.000000,0.0,...,6.403075,8.594354,10.243079,9.139459,10.102934,11.641081,10.607358,9.844794,4.550716,0.000000

## ***Checking for NaN Values***

In [57]:
for col in dataset.columns:
  if dataset[col].isnull().sum() > 0:
    print(col)
# No NaN Values found

## ***Encoding Categorical Data using Label Transformer***

In [58]:
dataset['Cancer Type'].unique()
le = preprocessing.LabelEncoder()
le.fit(dataset['Cancer Type'])
print(le.classes_)
encoded_cancer_type = le.transform(dataset['Cancer Type'])
for i in range (0,801):
  #dataset.iat[i,0] = labels.iat[i,1]
  dataset['Cancer Type'] = dataset['Cancer Type'].replace(dataset.iat[i,0], encoded_cancer_type[i])
dataset

['BRCA' 'COAD' 'KIRC' 'LUAD' 'PRAD']

,Cancer Type,gene_0,gene_1,gene_2,gene_3,gene_4,gene_5,gene_6,gene_7,gene_8,...,gene_20521,gene_20522,gene_20523,gene_20524,gene_20525,gene_20526,gene_20527,gene_20528,gene_20529,gene_20530
0,4,0.0,2.017209,3.265527,5.478487,10.431999,0.0,7.175175,0.591871,0.0,...,4.926711,8.210257,9.723516,7.220030,9.119813,12.003135,9.650743,8.921326,5.286759,0.000000
1,3,0.0,0.592732,1.588421,7.586157,9.623011,0.0,6.816049,0.000000,0.0,...,4.593372,7.323865,9.740931,6.256586,8.381612,12.674552,10.517059,9.397854,2.094168,0.000000
2,4,0.0,3.511759,4.327199,6.881787,9.870730,0.0,6.972130,0.452595,0.0,...,5.125213,8.127123,10.908640,5.401607,9.911597,9.045255,9.788359,10.090470,1.683023,0.000000
3,4,0.0,3.663618,4.507649,6.659068,10.196184,0.0,7.843375,0.434882,0.0,...,6.076566,8.792959,10.141520,8.942805,9.601208,11.392682,9.694814,9.684365,3.292001,0.000000
4,0,0.0,2.655741,2.821547,6.539454,9.738265,0.0,6.566967,0.360982,0.0,...,5.996032,8.891425,10.373790,7.181162,9.846910,11.922439,9.217749,9.461191,5.110372,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
796,0,0.0,1.865642,2.718197,7.350099,10.006003,0.0,6.764792,0.496922,0.0,...,6.088133,9.118313,10.004852,4.484415,9.614701,12.031267,9.813063,10.092770,8.819269,0.000000
797,3,0.0,3.942955,4.453807,6.346597,10.056868,0.0,7.320331,0.000000,0.0,...,6.371876,9.623335,9.823921,6.555327,9.064002,11.633422,10.317266,8.745983,9.659081,0.000000
798,1,0.0,3.249582,3.707492,8.185901,9.504082,0.0,7.536589,1.811101,0.0,...,5.719386,8.610704,10.485517,3.589763,9.350636,12.180944,10.681194,9.466711,4.677458,0.586693
799,4,0.0,2.590339,2.787976,7.318624,9.987136,0.0,9.213464,0.000000,0.0,...,5.785237,8.605387,11.004677,4.745888,9.626383,11.198279,10.335513,10.400581,5.718751,0.000000
800,4,0.0,2.325242,3.805932,6.530246,9.560367,0.0,7.957027,0.000000,0.0,...,6.403075,8.594354,10.243079,9.139459,10.102934,11.641081,10.607358,9.844794,4.550716,0.000000

## ***Split Dataset into Training Data and Test Data***

In [59]:
from sklearn.model_selection import train_test_split
dataset_train, dataset_test = train_test_split(dataset,test_size=0.2, shuffle=True, random_state=1)

## ***Training Data***

In [60]:
dataset_train

,Cancer Type,gene_0,gene_1,gene_2,gene_3,gene_4,gene_5,gene_6,gene_7,gene_8,...,gene_20521,gene_20522,gene_20523,gene_20524,gene_20525,gene_20526,gene_20527,gene_20528,gene_20529,gene_20530
309,0,0.000000,3.489029,3.511177,6.337722,10.198101,0.0,9.471700,0.000000,0.0,...,4.434948,7.963723,10.022493,6.094196,9.596326,11.963402,9.870138,9.515162,8.722060,0.000000
582,0,0.000000,5.774405,5.229730,6.083894,9.410716,0.0,5.759489,0.000000,0.0,...,5.698727,8.398577,10.455368,3.803020,9.472817,11.218587,10.864743,9.918766,4.272016,0.000000
593,0,0.000000,3.317434,3.038225,7.709615,10.256680,0.0,5.849079,0.834388,0.0,...,4.918157,8.475729,10.745893,7.986838,10.629484,11.430625,9.690192,11.158635,9.776882,0.000000
108,3,0.000000,2.480989,2.560446,7.026789,10.046537,0.0,5.643527,0.000000,0.0,...,5.222897,7.781530,9.610392,5.847346,9.966315,11.994916,9.122202,8.844226,4.175285,0.000000
798,1,0.000000,3.249582,3.707492,8.185901,9.504082,0.0,7.536589,1.811101,0.0,...,5.719386,8.610704,10.485517,3.589763,9.350636,12.180944,10.681194,9.466711,4.677458,0.586693
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
715,4,0.000000,4.748901,4.713602,6.453623,9.522389,0.0,8.807806,1.662844,0.0,...,6.247105,8.859861,10.410971,5.028087,9.772288,11.934078,10.825166,9.481876,8.142766,0.000000
767,1,0.000000,4.672505,5.151839,7.273012,9.688172,0.0,7.402969,0.000000,0.0,...,4.100641,8.951722,10.611237,1.417542,9.524299,12.566839,10.481204,9.616262,4.276824,0.000000
72,0,1.482332,2.907198,4.034365,6.613129,9.456295,0.0,10.038850,0.000000,0.0,...,5.147535,7.685660,10.155552,6.664853,8.469345,12.737940,10.332171,8.624295,8.378936,0.000000
235,4,0.000000,3.389553,3.391355,7.062424,9.286528,0.0,6.831067,0.000000,0.0,...,6.399429,8.872764,9.757512,6.017655,10.440807,11.695093,10.471381,9.785054,6.537920,0.000000
37,3,0.000000,4.416259,4.188978,6.664198,9.070819,0.0,7.915318,0.906275,0.0,...,5.786609,8.302470,10.431884,2.168899,9.402496,12.072283,10.637458,9.379959,6.148450,0.906275

## ***Testing Data***

In [61]:
dataset_test

,Cancer Type,gene_0,gene_1,gene_2,gene_3,gene_4,gene_5,gene_6,gene_7,gene_8,...,gene_20521,gene_20522,gene_20523,gene_20524,gene_20525,gene_20526,gene_20527,gene_20528,gene_20529,gene_20530
8,0,0.0,3.992125,2.772730,6.546692,10.488252,0.0,7.690222,0.352307,0.0,...,6.721974,9.597533,9.763753,7.933278,10.952880,12.498919,10.389954,10.390255,7.828321,0.000000
788,4,0.0,4.869200,4.087717,6.369039,9.684507,0.0,7.929903,0.000000,0.0,...,6.029753,8.875998,10.766554,6.197223,10.013392,9.939708,10.591896,10.316972,3.412782,0.000000
570,1,0.0,3.223716,3.027490,9.173387,10.057410,0.0,7.236426,0.600745,0.0,...,5.940963,8.564466,10.373311,0.000000,8.904803,11.991256,10.228650,9.914923,3.950730,0.000000
224,3,0.0,2.126246,3.513529,6.071696,9.565211,0.0,7.698996,0.000000,0.0,...,6.427449,8.759602,9.855941,7.042207,10.049181,13.044889,10.373757,10.077737,4.234279,0.418136
496,4,0.0,4.279924,3.606963,5.706613,9.716581,0.0,8.244226,0.402613,0.0,...,5.979975,8.461332,10.034744,4.809193,9.926295,10.827517,10.476949,9.734679,9.181547,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
671,0,0.0,2.526920,2.660381,6.667552,9.647475,0.0,7.609821,0.000000,0.0,...,6.192766,9.793984,10.003110,5.559486,9.733475,11.646473,10.550958,9.779411,5.511221,0.000000
364,2,0.0,0.000000,2.275752,6.025051,10.181674,0.0,6.112777,0.565890,0.0,...,5.402804,7.875964,10.120121,2.412185,9.498614,12.894869,10.434430,9.048045,7.690501,0.000000
674,4,0.0,4.229896,4.028003,7.032894,9.754323,0.0,7.567378,0.612777,0.0,...,6.524023,9.406613,10.242114,6.635736,10.744834,10.559951,10.714941,10.237688,6.260805,0.000000
41,4,0.0,3.026375,4.364103,7.164917,9.552402,0.0,7.903520,0.638862,0.0,...,5.867442,8.526257,9.960788,5.960727,9.934746,11.477040,10.126692,9.417869,8.367406,0.000000
666,3,0.0,3.798320,4.743278,7.034755,9.537941,0.0,9.337464,0.000000,0.0,...,6.418467,9.279216,10.021327,6.142683,9.255524,11.276090,9.865248,9.488581,3.311779,0.673828

## ***Feature Scaling of Training and Testing Data***

In [62]:
from sklearn.preprocessing import StandardScaler
sc =  StandardScaler()
col_header = list(dataset.columns)
del col_header[0]
dataset_train[col_header] = sc.fit_transform(dataset_train[col_header])
dataset_test[col_header] = sc.fit_transform(dataset_test[col_header])

In [63]:
dataset_train

,Cancer Type,gene_0,gene_1,gene_2,gene_3,gene_4,gene_5,gene_6,gene_7,gene_8,...,gene_20521,gene_20522,gene_20523,gene_20524,gene_20525,gene_20526,gene_20527,gene_20528,gene_20529,gene_20530
309,0,-0.193048,0.373727,0.393073,-0.599432,0.772786,0.0,1.888189,-1.008690,-0.130714,...,-1.915943,-1.318631,-0.084966,0.515497,-0.279127,0.358062,-0.484338,-0.148773,1.550381,-0.263436
582,0,-0.193048,2.297751,1.996768,-0.994205,-0.773635,0.0,-1.482131,-1.008690,-0.130714,...,-0.256797,-0.601933,1.043116,-0.453517,-0.510815,-0.776840,1.190425,0.572313,-0.623773,-0.263436
593,0,-0.193048,0.229264,-0.048269,1.534247,0.887835,0.0,-1.400792,0.671824,-0.130714,...,-1.281564,-0.474775,1.800228,1.315958,1.658950,-0.453750,-0.787340,2.787480,2.065735,-0.263436
108,3,-0.193048,-0.474927,-0.494116,0.472261,0.475115,0.0,-1.587413,-1.008690,-0.130714,...,-0.881488,-1.618909,-1.158909,0.411096,0.414927,0.406081,-1.743748,-1.347477,-0.671033,-0.263436
798,1,-0.193048,0.172140,0.576267,2.275006,-0.590265,0.0,0.131300,2.638991,-0.130714,...,-0.229675,-0.252319,1.121685,-0.543710,-0.740010,0.689540,0.881356,-0.235336,-0.425687,1.394498
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
715,4,-0.193048,1.434395,1.515135,-0.419173,-0.554309,0.0,1.285439,2.340391,-0.130714,...,0.463138,0.158325,0.927414,0.064605,0.050957,0.313380,1.123782,-0.208242,1.267356,-0.263436
767,1,-0.193048,1.370077,1.924082,0.855208,-0.228714,0.0,0.009987,-1.008690,-0.130714,...,-2.354836,0.309724,1.449312,-1.462415,-0.414241,1.277543,0.544603,0.031854,-0.621424,-0.263436
72,0,12.165173,-0.116107,0.881295,-0.171096,-0.684119,0.0,2.403105,-1.008690,-0.130714,...,-0.980427,-1.776916,0.261788,0.756847,-2.393204,1.538257,0.293654,-1.740409,1.382742,-0.263436
235,4,-0.193048,0.289980,0.281260,0.527684,-1.017541,0.0,-0.509245,-1.008690,-0.130714,...,0.663116,0.179591,-0.775512,0.483126,1.305015,-0.050770,0.528062,0.333419,0.483278,-0.263436
37,3,-0.193048,1.154348,1.025574,-0.091669,-1.441192,0.0,0.475148,0.816610,-0.130714,...,-0.141421,-0.760330,0.981915,-1.144641,-0.642727,0.523969,0.807711,-0.390329,0.292995,2.297606

In [64]:
dataset_test

,Cancer Type,gene_0,gene_1,gene_2,gene_3,gene_4,gene_5,gene_6,gene_7,gene_8,...,gene_20521,gene_20522,gene_20523,gene_20524,gene_20525,gene_20526,gene_20527,gene_20528,gene_20529,gene_20530
8,0,-0.214569,0.902153,-0.331593,-0.277908,1.296701,0.0,0.204350,-0.259864,-0.108761,...,1.201504,1.403134,-0.825780,1.307508,2.285424,0.975873,0.468470,1.438106,1.097632,-0.258350
788,4,-0.214569,1.610419,0.935674,-0.564451,-0.334531,0.0,0.416481,-0.896364,-0.108761,...,0.182865,0.173469,1.961541,0.597117,0.530318,-2.582919,0.855175,1.311156,-0.937124,-0.258350
570,1,-0.214569,0.281639,-0.086078,3.958778,0.422290,0.0,-0.197282,0.188982,-0.108761,...,0.052205,-0.357456,0.868508,-1.938777,-1.540696,0.269926,0.159585,0.614680,-0.689228,-0.258350
224,3,-0.214569,-0.604602,0.382322,-1.044046,-0.576647,0.0,0.212116,-0.896364,-0.108761,...,0.768094,-0.024898,-0.569540,0.942883,0.597178,1.735089,0.437454,0.896726,-0.558564,0.779231
496,4,-0.214569,1.134560,0.472366,-1.632900,-0.269435,0.0,0.694672,-0.168977,-0.108761,...,0.109613,-0.533220,-0.072552,0.029137,0.367606,-1.348348,0.635059,0.302440,1.721222,-0.258350
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
671,0,-0.214569,-0.281045,-0.439865,-0.082970,-0.409689,0.0,0.133192,-0.896364,-0.108761,...,0.422747,1.737932,-0.160479,0.336156,0.007389,-0.209523,0.776782,0.379930,0.029873,-0.258350
364,2,-0.214569,-2.321611,-0.810536,-1.119281,0.674490,0.0,-1.191768,0.126009,-0.108761,...,-0.739724,-1.530825,0.164757,-0.951715,-0.431367,1.526473,0.553639,-0.887028,1.034122,-0.258350
674,4,-0.214569,1.094161,0.878127,0.506304,-0.192836,0.0,0.095627,0.210719,-0.108761,...,0.910208,1.077762,0.503841,0.776555,1.896763,-1.720422,1.090797,1.173812,0.375294,-0.258350
41,4,-0.214569,0.122280,1.202029,0.719247,-0.602643,0.0,0.393130,0.257845,-0.108761,...,-0.055985,-0.422573,-0.278115,0.500343,0.383395,-0.445134,-0.035658,-0.246375,1.346052,-0.258350
666,3,-0.214569,0.745650,1.567444,0.509305,-0.631993,0.0,1.662242,-0.896364,-0.108761,...,0.754877,0.860647,-0.109845,0.574799,-0.885496,-0.724572,-0.536305,-0.123879,-0.983667,1.413716

## ***Extracting Data for each cancer type***

In [65]:
cancer_type0 = dataset_train.loc[dataset_train['Cancer Type']==0]
cancer_type0

,Cancer Type,gene_0,gene_1,gene_2,gene_3,gene_4,gene_5,gene_6,gene_7,gene_8,...,gene_20521,gene_20522,gene_20523,gene_20524,gene_20525,gene_20526,gene_20527,gene_20528,gene_20529,gene_20530
309,0,-0.193048,0.373727,0.393073,-0.599432,0.772786,0.0,1.888189,-1.008690,-0.130714,...,-1.915943,-1.318631,-0.084966,0.515497,-0.279127,0.358062,-0.484338,-0.148773,1.550381,-0.263436
582,0,-0.193048,2.297751,1.996768,-0.994205,-0.773635,0.0,-1.482131,-1.008690,-0.130714,...,-0.256797,-0.601933,1.043116,-0.453517,-0.510815,-0.776840,1.190425,0.572313,-0.623773,-0.263436
593,0,-0.193048,0.229264,-0.048269,1.534247,0.887835,0.0,-1.400792,0.671824,-0.130714,...,-1.281564,-0.474775,1.800228,1.315958,1.658950,-0.453750,-0.787340,2.787480,2.065735,-0.263436
415,0,-0.193048,0.326433,-0.433580,-0.252945,-0.879674,0.0,0.419128,0.800129,-0.130714,...,1.171269,2.630849,0.315853,0.384521,0.284458,0.055706,1.129626,-0.337392,-0.382745,-0.263436
708,0,-0.193048,1.013086,0.911268,-0.952067,-0.655944,0.0,0.246989,1.360247,-0.130714,...,0.434633,0.117947,0.829585,0.573036,0.597138,-0.010219,1.312959,1.318175,0.260783,-0.263436
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
668,0,-0.193048,0.655763,0.196235,-0.144113,0.062463,0.0,0.524080,-0.193846,-0.130714,...,0.024129,0.231612,0.029418,0.715908,0.408747,-0.194002,-0.988469,0.722299,-0.079963,-0.263436
276,0,4.524781,0.707178,-0.104628,-1.050257,0.609840,0.0,0.059998,0.947565,-0.130714,...,0.078564,0.472791,1.347922,0.540064,1.038126,0.583006,-0.601006,1.131085,-0.284607,-0.263436
178,0,-0.193048,-1.382703,-1.849155,0.097230,0.944699,0.0,-1.361469,-1.008690,-0.130714,...,0.010165,-0.374073,-0.228992,-0.577038,-0.138364,0.425497,-0.580854,0.354207,-0.308909,-0.263436
281,0,-0.193048,1.350957,1.700423,-0.017061,-1.613568,0.0,0.295741,-1.008690,-0.130714,...,0.653750,0.766667,1.532109,0.302521,0.685981,1.214302,0.865876,0.881656,0.876432,-0.263436
72,0,12.165173,-0.116107,0.881295,-0.171096,-0.684119,0.0,2.403105,-1.008690,-0.130714,...,-0.980427,-1.776916,0.261788,0.756847,-2.393204,1.538257,0.293654,-1.740409,1.382742,-0.263436

In [66]:
cancer_type1 = dataset_train.loc[dataset_train['Cancer Type']==1]
cancer_type1

,Cancer Type,gene_0,gene_1,gene_2,gene_3,gene_4,gene_5,gene_6,gene_7,gene_8,...,gene_20521,gene_20522,gene_20523,gene_20524,gene_20525,gene_20526,gene_20527,gene_20528,gene_20529,gene_20530
798,1,-0.193048,0.172140,0.576267,2.275006,-0.590265,0.0,0.131300,2.638991,-0.130714,...,-0.229675,-0.252319,1.121685,-0.543710,-0.740010,0.689540,0.881356,-0.235336,-0.425687,1.394498
363,1,-0.193048,0.068514,-1.267225,1.771141,0.133565,0.0,0.288909,0.084951,-0.130714,...,-1.252207,-1.166995,-1.198860,-1.832287,-1.268207,2.436245,0.382937,-1.153524,-0.172488,-0.263436
353,1,-0.193048,-0.032601,0.470382,1.477507,-0.480911,0.0,0.920145,0.099672,-0.130714,...,-0.447064,0.000337,-0.693213,-1.249575,-0.873589,0.594134,1.344940,-1.114864,-1.335645,1.291684
132,1,-0.193048,-1.196131,-0.195883,1.751407,0.307372,0.0,0.031182,-1.008690,-0.130714,...,-0.241037,-0.087252,-1.404779,-1.736844,-2.075283,0.614044,0.131318,-1.055497,-1.377660,-0.263436
473,1,-0.193048,-0.310164,-2.883435,0.926456,0.394983,0.0,0.252820,0.069955,-0.130714,...,0.202051,-0.513467,-0.889401,-1.835436,-1.147944,1.784749,-0.126739,-1.472108,0.248804,-0.263436
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
264,1,-0.193048,0.096927,-0.389536,2.482130,0.855997,0.0,-0.205941,-1.008690,-0.130714,...,-0.106301,-0.131399,-0.531156,-1.817312,-1.556597,1.342343,0.783511,-0.938898,-0.069328,-0.263436
503,1,-0.193048,0.407038,0.100584,1.614733,0.829240,0.0,-1.354905,0.021238,-0.130714,...,-2.450315,-1.922115,-0.701624,-2.061940,-1.323169,0.354983,2.053605,-1.716581,-1.155851,-0.263436
490,1,-0.193048,1.549663,1.321377,1.716448,-0.605728,0.0,-0.193361,-0.012800,-0.130714,...,-0.900310,-0.841090,-0.421155,-1.470693,-0.867451,0.274248,2.185612,-0.337487,-1.564186,-0.263436
252,1,-0.193048,-0.535684,-0.699357,0.725351,0.003692,0.0,-0.913283,-1.008690,-0.130714,...,0.039806,-0.329405,-0.803383,-1.604404,0.289934,2.852846,0.785358,-0.727938,0.572179,-0.263436
767,1,-0.193048,1.370077,1.924082,0.855208,-0.228714,0.0,0.009987,-1.008690,-0.130714,...,-2.354836,0.309724,1.449312,-1.462415,-0.414241,1.277543,0.544603,0.031854,-0.621424,-0.263436

In [67]:
cancer_type2 = dataset_train.loc[dataset_train['Cancer Type']==2]
cancer_type2

,Cancer Type,gene_0,gene_1,gene_2,gene_3,gene_4,gene_5,gene_6,gene_7,gene_8,...,gene_20521,gene_20522,gene_20523,gene_20524,gene_20525,gene_20526,gene_20527,gene_20528,gene_20529,gene_20530
430,2,-0.193048,-2.563634,-1.666383,0.350784,-1.340464,0.0,-2.560662,-1.008690,-0.130714,...,1.015250,-0.031233,-0.170037,-2.061940,1.320992,-0.471590,-0.377631,-0.288364,0.330797,1.012275
555,2,-0.193048,-0.672929,-1.240461,0.594826,-1.612023,0.0,-1.860653,-1.008690,-0.130714,...,1.862661,0.380910,-0.190466,0.163124,1.780776,-0.683901,0.424128,0.575754,-0.049393,-0.263436
482,2,-0.193048,-0.427355,-1.442821,-0.856775,0.255208,0.0,-2.187323,-1.008690,-0.130714,...,-0.248817,-0.647202,-0.921573,-0.082350,0.229608,0.316008,0.094617,-0.839912,0.034671,-0.263436
592,2,-0.193048,0.501379,-0.896708,-1.049511,0.261779,0.0,1.418035,0.856030,-0.130714,...,-0.260462,-1.228946,0.372833,-1.433791,-0.456831,1.098320,-0.550566,-0.510982,1.519368,-0.263436
223,2,-0.193048,-0.147084,-1.699609,-0.321915,-1.015495,0.0,-0.651248,0.654007,-0.130714,...,1.474677,-0.335665,-0.916036,0.471337,0.839088,-0.124978,0.568382,0.512652,-0.659137,-0.263436
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
534,2,4.418686,0.579458,0.336426,-1.024846,-0.893020,0.0,-0.039436,0.078362,-0.130714,...,2.224168,0.102442,0.559807,-0.054065,2.064048,0.160022,0.709142,-0.017175,-0.536349,-0.263436
319,2,-0.193048,0.042750,0.118396,-0.819881,-0.934698,0.0,0.527786,1.307307,-0.130714,...,0.714520,-0.293643,0.173001,-1.699004,0.129478,0.482993,0.527052,-1.397194,0.518697,-0.263436
468,2,-0.193048,-0.678576,-2.083317,-1.277032,-1.833116,0.0,-2.457601,-1.008690,-0.130714,...,2.461495,0.909605,-1.367678,0.042991,1.491329,-0.505621,0.836953,-0.024506,0.306309,-0.263436
357,2,-0.193048,-1.445148,-0.322358,0.548271,-1.595834,0.0,-1.565392,-1.008690,-0.130714,...,1.201144,-0.107706,0.490598,-0.490779,0.879901,-0.984189,0.215312,-0.319110,-0.317067,-0.263436
583,2,-0.193048,-1.077757,-1.077754,-0.381835,-1.236349,0.0,-1.590605,-1.008690,-0.130714,...,0.952707,0.055310,0.288820,-1.163869,1.434483,0.097723,1.038952,-1.145137,0.151975,-0.263436

In [68]:
cancer_type3 = dataset_train.loc[dataset_train['Cancer Type']==3]
cancer_type3

,Cancer Type,gene_0,gene_1,gene_2,gene_3,gene_4,gene_5,gene_6,gene_7,gene_8,...,gene_20521,gene_20522,gene_20523,gene_20524,gene_20525,gene_20526,gene_20527,gene_20528,gene_20529,gene_20530
108,3,-0.193048,-0.474927,-0.494116,0.472261,0.475115,0.0,-1.587413,-1.008690,-0.130714,...,-0.881488,-1.618909,-1.158909,0.411096,0.414927,0.406081,-1.743748,-1.347477,-0.671033,-0.263436
345,3,-0.193048,1.366094,2.311980,-1.799701,-0.273678,0.0,-0.031064,-0.254399,-0.130714,...,0.310149,-0.356373,0.180149,-1.673782,0.571013,0.023061,-1.429850,0.348843,-0.549987,0.794894
187,3,-0.193048,0.710601,0.943635,-0.232796,-0.416932,0.0,0.088499,-0.260008,-0.130714,...,-0.639246,-0.924745,-1.411908,0.764187,-0.016184,0.677277,-0.115362,-1.102835,-0.660427,0.787025
159,3,-0.193048,0.598404,1.398975,-0.438818,-0.718192,0.0,0.856962,0.119446,-0.130714,...,-0.298389,-0.694844,0.241031,0.688127,0.476265,0.587955,0.314706,-0.871973,-0.261322,-0.263436
161,3,-0.193048,2.004066,1.972629,0.049627,-1.101584,0.0,0.242026,-0.138833,-0.130714,...,0.016104,0.090877,2.853590,-1.145510,-0.019663,-1.579081,2.066365,-0.097080,2.189747,-0.263436
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
749,3,-0.193048,0.447590,0.518510,-0.155629,0.716784,0.0,-0.805796,-1.008690,-0.130714,...,0.910762,0.486115,-0.040730,0.151737,-0.664581,-1.902097,0.641651,-1.113092,-0.735807,-0.263436
129,3,-0.193048,0.214086,-0.425878,1.706235,0.079581,0.0,0.662781,0.508087,-0.130714,...,-1.516898,-1.153282,-0.832239,-1.154186,0.492455,0.797446,-1.866556,0.776201,-2.343011,-0.263436
144,3,-0.193048,0.759910,0.958504,-0.179096,-1.543491,0.0,0.000768,-1.008690,-0.130714,...,0.830706,0.799529,-0.279741,-0.252793,1.466204,0.375608,0.049593,0.133434,0.317581,-0.263436
645,3,-0.193048,0.999353,-0.495943,-0.419857,-0.804378,0.0,1.072124,-0.150272,-0.130714,...,0.062996,0.504941,0.475805,0.918725,1.381477,0.227116,0.252644,1.105142,-0.847742,-0.263436
37,3,-0.193048,1.154348,1.025574,-0.091669,-1.441192,0.0,0.475148,0.816610,-0.130714,...,-0.141421,-0.760330,0.981915,-1.144641,-0.642727,0.523969,0.807711,-0.390329,0.292995,2.297606

In [69]:
cancer_type4 = dataset_train.loc[dataset_train['Cancer Type']==4]
cancer_type4

,Cancer Type,gene_0,gene_1,gene_2,gene_3,gene_4,gene_5,gene_6,gene_7,gene_8,...,gene_20521,gene_20522,gene_20523,gene_20524,gene_20525,gene_20526,gene_20527,gene_20528,gene_20529,gene_20530
0,4,-0.193048,-0.865376,0.163841,-1.935784,1.232160,0.0,-0.196828,0.183379,-0.130714,...,-1.270335,-0.912309,-0.864105,0.991650,-1.173007,0.418605,-0.853765,-1.209728,-0.128001,-0.263436
587,4,-0.193048,0.604770,0.588629,0.418028,0.554659,0.0,-0.246122,-1.008690,-0.130714,...,0.636085,0.109620,-0.270141,0.319381,0.925401,0.051451,1.063371,0.937840,0.150581,-0.263436
714,4,-0.193048,1.260196,2.252452,-0.434885,0.009198,0.0,1.089296,0.769250,-0.130714,...,0.413623,0.102101,0.350073,0.933790,0.041629,-1.003095,0.835355,0.766390,0.306505,-0.263436
657,4,-0.193048,1.009163,1.339732,0.956886,-0.893211,0.0,0.190944,-0.330241,-0.130714,...,1.148989,0.802213,0.478514,0.942307,1.011152,-0.651990,0.942498,-0.425517,-0.340409,0.688481
125,4,-0.193048,0.579841,0.232519,0.189412,-0.725149,0.0,1.278294,-1.008690,-0.130714,...,-0.298870,-0.865131,-0.803580,0.605451,0.179550,-0.056333,-0.462628,-0.015545,0.806196,-0.263436
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
478,4,-0.193048,0.745666,0.895491,0.014179,0.003176,0.0,-0.529475,-1.008690,-0.130714,...,1.036683,0.561085,0.275115,-0.284214,0.621185,-1.077075,1.023428,1.092768,-0.013702,-0.263436
254,4,-0.193048,1.650953,2.573757,-0.657722,-0.126131,0.0,0.946025,0.565783,-0.130714,...,0.546850,0.077301,1.334936,0.789689,-0.086175,-1.884118,0.762254,0.442665,-0.439511,-0.263436
390,4,-0.193048,-1.267150,1.927312,-0.631502,-0.233729,0.0,0.943185,-1.008690,-0.130714,...,-0.562820,-0.471551,-0.479595,0.704172,-0.265662,0.441630,0.066888,-0.297853,0.694273,-0.263436
715,4,-0.193048,1.434395,1.515135,-0.419173,-0.554309,0.0,1.285439,2.340391,-0.130714,...,0.463138,0.158325,0.927414,0.064605,0.050957,0.313380,1.123782,-0.208242,1.267356,-0.263436
235,4,-0.193048,0.289980,0.281260,0.527684,-1.017541,0.0,-0.509245,-1.008690,-0.130714,...,0.663116,0.179591,-0.775512,0.483126,1.305015,-0.050770,0.528062,0.333419,0.483278,-0.263436

## ***MLP Classifier***

In [70]:
#from sklearn.neural_network import MLPClassifier
#X = [[cancer_type0], [cancer_type1], [cancer_type2], [cancer_type3], [cancer_type4]]
#Y = [0,1,2,3,4]
#clf = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(20532, 5), random_state=1)
#clf.fit(X,Y)